### ISSUE TITLE
Error: File structure does not match the disk cache backend

### ISSUE THREAD

**Issue by rlivsey** [brzpegasus/ember-cli-node-webkit#10]
When trying to add this to an existing app I'm getting the following error (as shown in the screenshot below):

```
Starting nw.js...
[6367:0323/175152:ERROR:simple_version_upgrade.cc(153)] File structure does not match the disk cache backend.
[6367:0323/175152:ERROR:simple_backend_impl.cc(575)] Simple Cache Backend: wrong file structure on disk: /Users/rlivsey/Library/Application Support/minutebase/Cache
```

It's a fairly large app (running Ember Canary & Ember CLI 0.2.0) but everything's pretty standard Ember.

This is on Yosemite, with a case-sensitive file system - I wonder if that's got anything to do with it?

Here's a screenshot of the error & inspector output:

![screenshot 2015-03-23 17 54 05](https://cloud.githubusercontent.com/assets/3740/6786699/d40da4fa-d185-11e4-88a7-c73059706d28.png)

**Comment by brzpegasus** [comment]
I haven't run into this "File structure does not match the disk cache backend" error before, so I'm unclear what it's referring to.

However, you would typically get those `ERR_FILE_NOT_FOUND` errors in the console if the router's location type is set incorrectly. Do you mind verifying the value of `ENV.locationType` in your `config/environment.js`? It needs to be set to `'hash'`.

**Comment by rlivsey** [comment]
Ah d'oh, I missed that when generating and the location type was set to 'history' still.

That gets rid of that error, but now I'm seeing:

```
[9631:0324/111029:ERROR:nw_shell.cc(335)] Error: Cannot find module 'ember'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at file:///Users/rlivsey/Sites/minutebase/3/frontend/dist/assets/vendor.js:62360:13
    at file:///Users/rlivsey/Sites/minutebase/3/frontend/dist/assets/vendor.js:63898:3
[9631:0324/111029:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'ember'", source: module.js (329)
```

I'll dig into that and see if I can figure out what's going on - I'll close this particular issue for now.

Cheers.

**Comment by brzpegasus** [comment]
The "Error: Cannot find module 'ember'" message from `module.js` means it's attempting to load Ember using Node's `require` function rather than the one defined by Ember CLI's loader.

If you open up `dist/assets/vendor.js`, the first chunk of code you should see is the [shim](https://github.com/brzpegasus/ember-cli-node-webkit/blob/v0.2.0/blueprints/node-webkit/files/vendor/node-webkit/shim.js) that this addon inserts to deal with `require` name conflicts. The second piece of code should be the content of [bower_components/loader.js/loader.js](https://github.com/ember-cli/loader.js/blob/v3.2.1/loader.js):

```javascript
// dist/assets/vendor.js

/* jshint ignore:start */

window.EmberENV = {"FEATURES":{}};
var runningTests = false;

/* jshint ignore:end */

// Content from addon's shim.js
;(function(window) {
  if (!window.nwDispatcher) return;

  // Rename node's `require` to avoid conflicts with AMD's `require`.
  var requireNode = window.requireNode = window.require;
  delete window.require;

  // ...
  });
})(this);

// Content from loader.js
;var define, requireModule, require, requirejs;

(function() {
  // ...
  requirejs = require = requireModule = function(name) {
    // ...
  }
});
```

Either yours looks different, or that did not run correctly.

If you'd like a sample NW.js app setup while you're debugging, you could refer to this [example](https://github.com/brzpegasus/ember-nw-markdown). I'm very curious to know if this happens to be some use case I had not thought of before but should be covered, which is entirely possible.

If you get stuck, I'd be happy to look at your repo. We can do a hangout or something if that helps. Feel free to bug me.

**Comment by rlivsey** [comment]
Cool thanks, I'll dig into that this evening and see if I can figure out what's gone awry.
