### ISSUE TITLE
Doesn't work with frontend packages such as moment.js

### ISSUE THREAD

**Issue by runspired** [brzpegasus/ember-cli-node-webkit#16]
I tried wrapping an Ember app that uses `moment.js` and it errors out that `moment` is not defined (this same app currently works in Cordova environments and in browser).

**Comment by runspired** [comment]
moment's function for attaching it to a global context checks if "global" is a variable, which it is in node-webkit.  To have an app use moment normally, the easy hack is to add `window.moment = window.moment || window.global ? window.global.moment : undefined;`

**Comment by dstaley** [comment]
@runspired where are you adding that code?

**Comment by runspired** [comment]
@dstaley I have an initializer that set's up moment, it's at the top of that file.

**initializers/moment.js**
```
window.moment = window.moment || window.global ? window.global.moment : undefined;

export default {
  name: "momentjs",
  before: "store",
  initialize: function () {
    moment.locale('en', {
      relativeTime : {
        future: "just now",
        past:   "%s",
        s:  "seconds ago",
        m:  "a minute ago",
        mm: "%d minutes ago",
        h:  "an hour ago",
        hh: "%d hours ago",
        d:  "yesterday",
        dd: "%d days ago",
        M:  "a month ago",
        MM: "%d months ago",
        y:  "a year ago",
        yy: "%d years ago"
      }
    });

  }
};
```

**Comment by runspired** [comment]
Also looks like this was previously noted: https://github.com/brzpegasus/ember-cli-node-webkit/issues/5

**Comment by brzpegasus** [comment]
There have been issues with moment.js in the past. The way they detect the environment (Node vs. browser) has also changed over time. When I last visited this, I put in a fix in `shim.js` to work with moment.js >= 2.8.4, given this [commit](https://github.com/moment/moment/commit/1601cb1dd7b14277ba8b00cb2ece3ce637923080). It looks like in the latest version, they just set the global scope to be whatever `this` is, which _should_ be fine but I'll need to confirm. Which version of moment are you using?

The workaround you have is fine. Perhaps a slightly better way would be to create a module that exports the correct value (either `window.moment` or `window.global.moment`). That way, you can simply import the module wherever you need to use `moment`, instead of accessing it via the global namespace. Something like:

```javascript
// ./moment.js (just a simple shim)
export default window.moment || global.moment;
```

```javascript
// some other module that needs `moment`
import moment from './moment';

var now = moment();
```
