### ISSUE TITLE
Installing addon breaks `ember test`

### ISSUE THREAD

**Issue by alexlafroscia** [brzpegasus/ember-cli-node-webkit#35]
Since trying out this package today, my regular tests (`ember test`) seem to fail.  I've even tested it with a brand new repo; if you make the repo and immediately run `ember test` then you should get 5 JSHint tests passing. If you then install `ember-cli-node-webkit` and run `ember test` again, the tests will hang after successfully building the project but before the tests run.

**Comment by sedouard** [comment]
Hey there! @brzpegasus and myself worked on getting tests running within nwjs -- which requires a slightly different command. Its probably because of this the regular command is broken. I don't think we checked to see if we broke that command.

For [my project](http://storageexplorer.com) we just use `ember nw:test`/ `ember nw:test --server` and it works great. Is there a reason you need to run tests outside of nwjs?

**Comment by alexlafroscia** [comment]
Yeah, so we're looking to use NW to build a `win32` app that can be deployed to old computers that run xP and IE 8 (so that we can lessen the amount of IE 8 users we have).  However, we still need the app to work in browsers.  Is that not really something that can be done with NW? Also, if you see my other issue ( #34 ) I am getting some weird behavior when trying to run the app in anything other than the `production` environment.

**Comment by brzpegasus** [comment]
@alexlafroscia Thanks for checking this out! The addon makes changes to the broccoli build when `process.env.EMBER_ENV === 'test'` in order to support loading the test runner page in NW. This does mean those changes would be applied when you execute `ember test` (though, I realize, undesirably).

I can make a quick fix to let the customizations to the broccoli build execute only when you run `ember nw:test` and not `ember test`. I may not be able to get to it until tomorrow night or so though.

**Comment by alexlafroscia** [comment]
No problem! Thanks for the help, I really appreciate it! Knowing that now, I"ll see if I can get a PR together myself this evening, if you think it's something I might be able to figure out.

**Comment by alexlafroscia** [comment]
I looked into that environment variables are available do the `index.js` file within `postprocessTree()`and the only difference between running `ember test` and `ember nw:test` seems to be that the former has `EMBER_CLI_TEST_OUTPUT` defined.  Is it enough to check that? Or would you hook in at a different place?

**Comment by brzpegasus** [comment]
Yeah, unfortunately there's no good way for the addon to know which command is being run from that hook, other than relying on environment variables (as far as I know). I was thinking the `nw-test` command could set a property on `process.env` in its `run` hook, which the addon's `index.js` can then refer to, something like `process.env.NW_TEST`.

**Comment by alexlafroscia** [comment]
Gotcha. Do you want me to give it a shot? I'd be happy to.

**Comment by brzpegasus** [comment]
@alexlafroscia Sure! Just holler if you need me to jump in at any time. I'll look at your other issue soon.
